k8s jenkins

diff --git a/ci/k8s/Jenkinsfile b/ci/k8s/Jenkinsfile
--- a/ci/k8s/Jenkinsfile
+++ b/ci/k8s/Jenkinsfile
@@ -67,7 +67,7 @@ spec:
                         #/kaniko/executor --context ./ --dockerfile deploy/docker/base/Dockerfile\
                         #   --destination $REPO_PREFIX/f7t-base:$GIT_COMMIT_SHORT --cleanup
 
-                        for ms in status certificator compute storage tasks utilities reservations; do
+                        for ms in certificator compute reservations status storage tasks utilities; do
                             /kaniko/executor --build-arg BASE_IMAGE=$REPO_PREFIX/f7t-base:latest --registry-mirror $REGISTRY \
                               --context ./ --dockerfile deploy/docker/$ms/Dockerfile --destination $REPO_PREFIX/$ms:$GIT_COMMIT_SHORT --cleanup
                         done
@@ -193,6 +193,7 @@ spec:
     post{
         always {
             withKubeConfig([credentialsId: 'firecrest-cicd-secret', serverUrl: K8S_CLUSTER_URL]) {
+              withCredentials([string(credentialsId: 'JFROG_API_KEY', variable: 'JFROG_API_KEY')]) {
                 sh '''
                     # installing kubectl
                     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
@@ -217,8 +218,14 @@ spec:
                         helm uninstall "$app-env-dev" -n "$DEPLOY_NAMESPACE" || true
                     done
 
+                    # remove images
+                    for ms in certificator compute reservations status storage tasks tester utilities; do
+                        img="$REPO_PREFIX/$ms/$GIT_COMMIT_SHORT"
+                        curl -u $REGISTRY_USER:$JFROG_API_KEY -XDELETE $img  && echo "Deleted: $img" || echo "Failed to delete: $img"
+                    done
                 '''
             }
+          }
         }
         success {
             script {
